name: "Test"
on:
  pull_request:
    branch: ["main"]
  push:
    branch: ["**"]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix run .#test
